In [1]:
import pickle
import numpy as np

In [3]:
save_file = '/Users/komei0727/workspace/robot_intelligence/data/mnist.pkl'
with open(save_file, 'rb') as f:
    dataset = pickle.load(f)

train_img,train_label,test_img,test_label = dataset

#画素値を0~1の間の値に変換
train_img = train_img / 255
test_img = test_img / 255
train_img = train_img.astype(np.float32)
#ラベルをone-hot表現で表す
train_label = [int(x) for x in train_label]
train_label_one_hot = np.identity(10)[train_label].astype(np.float32)
test_label = [int(x) for x in test_label]
test_label_one_hot = np.identity(10)[test_label]

In [4]:
W1 = np.random.normal(loc = 0.0, scale = np.sqrt(1.0/784), size = (784, 200)).astype(np.float32)
W2 = np.random.normal(loc = 0.0, scale = np.sqrt(1.0/200), size = (200, 10)).astype(np.float32)
b1 = np.zeros(shape = (1, 200), dtype = np.float32)
b2 = np.zeros(shape = (1, 10), dtype = np.float32)

In [46]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def softmax(x):
    e = np.exp(x)
    return e / np.sum(e)

def sigmoid_dash(x):
    return x * (1 - x)

def cross_entropy(y, t):
    E = 0.0
    for i in range(len(t[0])):
        E = E - t[0][i]*np.log(y[0][i])
    return E.astype(np.float32)

In [5]:
x = train_img[0]

In [6]:
u1 = np.dot(x, W1) + b1

In [12]:
z1 = sigmoid(u1)

In [14]:
u2 = np.dot(z1, W2) + b2

In [17]:
z2 = softmax(u2)

In [18]:
y = z2

In [19]:
d = train_label_one_hot[0]

In [22]:
delta2 = y - d

In [24]:
W2_g = np.dot(z1.T, delta2)

In [31]:
b2_g = delta2

In [53]:
delta1 = np.array([np.sum(delta2*W2*sigmoid_dash(z1).T, axis=1)])

In [66]:
W1_g = np.dot(np.array([x]).T, delta1)

In [56]:
b1_g = delta1

In [67]:
W1 - W1_g*0.01

array([[ 0.00563938,  0.01340188, -0.00315171, ...,  0.01072057,
         0.00303231, -0.01439671],
       [-0.03915057,  0.01406019, -0.02274988, ..., -0.0142651 ,
        -0.07670706,  0.03317168],
       [-0.03077852,  0.02211996,  0.01592824, ...,  0.00393565,
        -0.07758915,  0.03088435],
       ...,
       [ 0.01428768,  0.04127844, -0.05464423, ...,  0.04485237,
         0.00161294,  0.08793727],
       [-0.05904477,  0.01324437,  0.01449402, ..., -0.02551041,
         0.02313843, -0.01641174],
       [ 0.00485252,  0.03273388, -0.03287735, ...,  0.02532258,
        -0.05310793,  0.02236965]], dtype=float32)

In [68]:
W1

array([[ 0.00563938,  0.01340188, -0.00315171, ...,  0.01072057,
         0.00303231, -0.01439671],
       [-0.03915057,  0.01406019, -0.02274988, ..., -0.0142651 ,
        -0.07670706,  0.03317168],
       [-0.03077852,  0.02211996,  0.01592824, ...,  0.00393565,
        -0.07758915,  0.03088435],
       ...,
       [ 0.01428768,  0.04127844, -0.05464423, ...,  0.04485237,
         0.00161294,  0.08793727],
       [-0.05904477,  0.01324437,  0.01449402, ..., -0.02551041,
         0.02313843, -0.01641174],
       [ 0.00485252,  0.03273388, -0.03287735, ...,  0.02532258,
        -0.05310793,  0.02236965]], dtype=float32)

In [70]:
b2-b2_g*0.01

array([[-0.00053578, -0.00081073, -0.00118495, -0.0013949 , -0.00162032,
         0.00905319, -0.0009633 , -0.00065695, -0.00084571, -0.00104055]],
      dtype=float32)